In [1]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn import svm
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
df = pd.read_csv('glass.csv')
df.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [3]:
x = df.drop('Type', axis=1)
y = df['Type']

In [4]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=111)

In [5]:
model1 = SVC(kernel='sigmoid')
model2 = SVC(kernel='poly')
model3 = SVC(kernel='rbf')

In [6]:
model1.fit(x_train, y_train)
model2.fit(x_train, y_train)
model3.fit(x_train, y_train)

SVC()

In [7]:
y_pred1 = model1.predict(x_test)
y_pred2 = model2.predict(x_test)
y_pred3 = model3.predict(x_test)

In [8]:
print("Evaluation of Model 1 Sigmoid: ")
print(confusion_matrix(y_test, y_pred1))
print(accuracy_score(y_test,y_pred1))

Evaluation of Model 1 Sigmoid: 
[[12  3  0  0  0]
 [ 0 14  0  0  0]
 [ 0  5  0  0  0]
 [ 0  4  0  0  0]
 [ 0  5  0  0  0]]
0.6046511627906976


In [9]:
print("Evaluation of Model 2 Polynomial: ")
print(confusion_matrix(y_test, y_pred2))
print(accuracy_score(y_test,y_pred2))

Evaluation of Model 2 Polynomial: 
[[15  0  0  0  0  0]
 [ 1 13  0  0  0  0]
 [ 0  1  4  0  0  0]
 [ 0  0  0  2  2  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  5]]
0.9069767441860465


In [10]:
print("Evaluation of Model 3 RBF: ")
print(confusion_matrix(y_test, y_pred3))
print(accuracy_score(y_test,y_pred3))

Evaluation of Model 3 RBF: 
[[15  0  0  0  0]
 [ 0 14  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0  2  0  2]
 [ 0  0  0  0  5]]
0.7906976744186046
